import type {
  AppNotification,
  AuditEvent,
  CredentialApplication,
  IssuedCredential,
  MicroCredentialTemplate,
  MockUser,
  Organization,
  PlatformEvent,
  RegistrationRequest,
} from "./types";

export const mockOrganizations: Organization[] = [
  {
    id: "org-fos",
    name: "Faculty of Organizational Sciences",
    type: "issuer",
    country: "Serbia",
    about: "Leading higher education institution in organizational, information and management sciences.",
    website: "https://fon.bg.ac.rs",
    accreditations: ["MoESTD Serbia", "EURASHE", "EUNIS"],
    registeredAt: "2024-09-01T09:00:00Z",
  },
  {
    id: "org-w3hub",
    name: "Web3 Innovation Hub",
    type: "issuer",
    country: "Serbia",
    about: "Independent innovation hub specializing in decentralized technologies.",
    website: "https://web3hub.example",
    accreditations: ["EBSI Early Adopter Programme"],
    registeredAt: "2025-02-15T10:00:00Z",
  },
  {
    id: "org-ebiz",
    name: "Department for e-business",
    type: "issuer",
    country: "Serbia",
    about: "Academic department within FON focused on digital business and emerging technologies.",
    website: "https://ebusiness.fon.bg.ac.rs",
    accreditations: ["MoESTD Serbia"],
    registeredAt: "2024-09-01T09:00:00Z",
  },
];

export const mockUsers: MockUser[] = [
  { id: "u-e1", name: "Mila Petrović", email: "mila@student.fon.bg.ac.rs", role: "earner", studentId: "FON-2023-0142" },
  { id: "u-e2", name: "Luka Jovanović", email: "luka@student.fon.bg.ac.rs", role: "earner", studentId: "FON-2022-0815" },
  { id: "u-e3", name: "Sara Nikolić", email: "sara@student.fon.bg.ac.rs", role: "earner", studentId: "FON-2024-0003" },
  { id: "u-i1", name: "Prof. Stefan Kostić", email: "stefan@fon.bg.ac.rs", role: "issuer", organizationId: "org-fos", organization: "Faculty of Organizational Sciences" },
  { id: "u-i2", name: "Nina Radić", email: "nina@web3hub.example", role: "issuer", organizationId: "org-w3hub", organization: "Web3 Innovation Hub" },
  { id: "u-v1", name: "Nordic Tech HR", email: "hr@nordictech.eu", role: "verifier", organization: "Nordic Tech AB" },
  { id: "u-a1", name: "Platform Admin", email: "admin@microcred.example", role: "admin" },
];

export const mockTemplates: MicroCredentialTemplate[] = [
  {
    id: "tpl-blockchain",
    title: "Blockchain Fundamentals",
    description: "Introduction to blockchain concepts, smart contracts, consensus mechanisms and decentralized applications.",
    issuerId: "org-fos",
    issuerName: "Faculty of Organizational Sciences",
    country: "Serbia",
    source: "formal",
    outcomes: ["Understand blockchain concepts", "Deploy a basic smart contract", "Evaluate dApp use cases"],
    skills: ["Blockchain", "Smart contracts", "Solidity"],
    ects: 3,
    level: "Intermediate",
    assessment: "Written exam and project assignment",
    participation: "hybrid",
    qualityAssurance: "Internal QA — FON",
    prerequisites: "Basic programming knowledge",
    supervision: "Proctored exam",
    stackability: "Stacks toward MSc in Information Systems",
    expiryRule: "No expiry",
    status: "active",
    version: "1.2",
  },
  {
    id: "tpl-web3hack",
    title: "Web3 Hackathon Participation",
    description: "Apply blockchain concepts in team-based product development during a 48h hackathon.",
    issuerId: "org-w3hub",
    issuerName: "Web3 Innovation Hub",
    country: "Serbia",
    source: "non_formal",
    subcategory: "competition_hackathon",
    outcomes: ["Apply Web3 concepts", "Ship a prototype under time pressure", "Pitch to a jury"],
    skills: ["Teamwork", "Rapid prototyping", "Web3"],
    level: "Foundation",
    assessment: "Project prototype and pitch",
    participation: "onsite",
    qualityAssurance: "Jury panel",
    prerequisites: "None",
    supervision: "On-site mentors",
    stackability: "Recognized as elective at FON",
    status: "active",
    version: "2.0",
  },
  {
    id: "tpl-aibootcamp",
    title: "AI in E-Business Bootcamp",
    description: "Intensive bootcamp on applying AI for business process innovation.",
    issuerId: "org-ebiz",
    issuerName: "Department for e-business",
    country: "Serbia",
    source: "non_formal",
    subcategory: "workshop_bootcamp",
    outcomes: ["Use generative AI", "Prototype an end-to-end product", "Evaluate AI ethics"],
    skills: ["Generative AI", "Prototyping"],
    ects: 2,
    level: "Foundation",
    assessment: "Final assignment + live demo",
    participation: "hybrid",
    qualityAssurance: "Department QA committee",
    prerequisites: "Basic digital literacy",
    supervision: "Instructor-led sessions",
    stackability: "Counts toward CPD",
    status: "active",
    version: "1.1",
  },
];

const defaultSharing = {
  isPublic: true,
  showGrade: true,
  showSource: true,
  showExpiry: true,
  showSkills: true,
};

export const mockCredentials: IssuedCredential[] = [
  {
    id: "cred-001",
    templateId: "tpl-blockchain",
    title: "Blockchain Fundamentals",
    earnerId: "u-e1",
    earnerName: "Mila Petrović",
    issuerId: "org-fos",
    issuerName: "Faculty of Organizational Sciences",
    issuedAt: "2026-01-22T10:00:00Z",
    status: "active",
    source: "formal",
    level: "Intermediate",
    ects: 3,
    skills: ["Blockchain", "Smart contracts", "Solidity"],
    grade: "9 / 10",
    verificationLink: "/verify/cred-001",
    shareToken: "share-mila-001",
    sharing: defaultSharing,
    blockchain: { ebsiStatus: "not_anchored" },
  },
  {
    id: "cred-002",
    templateId: "tpl-web3hack",
    title: "Web3 Hackathon Participation",
    earnerId: "u-e1",
    earnerName: "Mila Petrović",
    issuerId: "org-w3hub",
    issuerName: "Web3 Innovation Hub",
    issuedAt: "2025-11-12T18:00:00Z",
    status: "active",
    source: "non_formal",
    subcategory: "competition_hackathon",
    level: "Foundation",
    skills: ["Teamwork", "Web3"],
    verificationLink: "/verify/cred-002",
    sharing: { ...defaultSharing, showGrade: false },
    blockchain: { ebsiStatus: "not_anchored" },
  },
  {
    id: "cred-003",
    templateId: "tpl-aibootcamp",
    title: "AI in E-Business Bootcamp",
    earnerId: "u-e2",
    earnerName: "Luka Jovanović",
    issuerId: "org-ebiz",
    issuerName: "Department for e-business",
    issuedAt: "2025-09-30T16:00:00Z",
    expiresAt: "2027-09-30T16:00:00Z",
    status: "active",
    source: "non_formal",
    subcategory: "workshop_bootcamp",
    level: "Foundation",
    ects: 2,
    skills: ["Generative AI", "Prototyping"],
    grade: "Pass with distinction",
    verificationLink: "/verify/cred-003",
    sharing: defaultSharing,
    blockchain: { ebsiStatus: "not_anchored" },
  },
];

export const mockApplications: CredentialApplication[] = [
  {
    id: "app-001",
    earnerId: "u-e1",
    earnerName: "Mila Petrović",
    templateId: "tpl-aibootcamp",
    templateTitle: "AI in E-Business Bootcamp",
    issuerId: "org-ebiz",
    issuerName: "Department for e-business",
    status: "in_review",
    reviewerComments: [],
    timeline: [
      { id: "t1", at: "2026-04-22T10:14:00Z", actor: "Mila Petrović", action: "Application submitted" },
      { id: "t2", at: "2026-04-23T08:30:00Z", actor: "Issuer", action: "Moved to In review" },
    ],
    createdAt: "2026-04-22T10:14:00Z",
    updatedAt: "2026-04-23T08:30:00Z",
  },
  {
    id: "app-002",
    earnerId: "u-e2",
    earnerName: "Luka Jovanović",
    templateId: "tpl-blockchain",
    templateTitle: "Blockchain Fundamentals",
    issuerId: "org-fos",
    issuerName: "Faculty of Organizational Sciences",
    status: "submitted",
    reviewerComments: [],
    timeline: [
      { id: "t1", at: "2026-04-20T09:00:00Z", actor: "Luka Jovanović", action: "Application submitted" },
    ],
    createdAt: "2026-04-20T09:00:00Z",
    updatedAt: "2026-04-20T09:00:00Z",
  },
];

export const mockNotifications: AppNotification[] = [
  { id: "n-2", forRole: "issuer", title: "New application submitted", body: "Mila Petrović — AI in E-Business Bootcamp", createdAt: "2026-04-22T10:15:00Z", read: false, link: "/issuer/requests" },
  { id: "n-4", forRole: "earner", forUserId: "u-e1", title: "Credential issued", body: "Blockchain Fundamentals is now in your wallet.", createdAt: "2026-01-22T10:01:00Z", read: true, link: "/earner/credentials" },
];

export const mockRegistrations: RegistrationRequest[] = [
  { id: "reg-1", type: "issuer", organizationName: "Innovation Centre Niš", contactName: "M. Mitić", contactEmail: "contact@icnis.example", country: "Serbia", submittedAt: "2026-05-01T09:00:00Z", status: "pending" },
];

export const mockAudit: AuditEvent[] = [
  { id: "a-5", at: "2026-01-22T10:00:00Z", actor: "Prof. Stefan Kostić", action: "issued credential", target: "cred-001" },
];

export const mockPlatformEvents: PlatformEvent[] = [
  { id: "p-4", at: "2026-04-10T10:00:00Z", type: "issuance", description: "Credential cred-003 issued to Luka Jovanović" },
];
