/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuersIndexRouteImport } from './routes/issuers.index'
import { Route as IssuerIndexRouteImport } from './routes/issuer.index'
import { Route as EarnerIndexRouteImport } from './routes/earner.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as ProfileTokenRouteImport } from './routes/profile.$token'
import { Route as IssuersIdRouteImport } from './routes/issuers.$id'
import { Route as IssuerStaffRouteImport } from './routes/issuer.staff'
import { Route as IssuerRevocationsRouteImport } from './routes/issuer.revocations'
import { Route as IssuerRequestsRouteImport } from './routes/issuer.requests'
import { Route as IssuerProfileRouteImport } from './routes/issuer.profile'
import { Route as IssuerEbsiRouteImport } from './routes/issuer.ebsi'
import { Route as IssuerEarnersRouteImport } from './routes/issuer.earners'
import { Route as IssuerCredentialsRouteImport } from './routes/issuer.credentials'
import { Route as EarnerSettingsRouteImport } from './routes/earner.settings'
import { Route as EarnerProfileRouteImport } from './routes/earner.profile'
import { Route as EarnerNotificationsRouteImport } from './routes/earner.notifications'
import { Route as EarnerApplyRouteImport } from './routes/earner.apply'
import { Route as EarnerApplicationsRouteImport } from './routes/earner.applications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as IssuerMicrocredential_templatesIndexRouteImport } from './routes/issuer.microcredential_templates.index'
import { Route as IssuerIssueIndexRouteImport } from './routes/issuer.issue.index'
import { Route as EarnerCredentialsIndexRouteImport } from './routes/earner.credentials.index'
import { Route as IssuerMicrocredential_templatesNewRouteImport } from './routes/issuer.microcredential_templates.new'
import { Route as IssuerMicrocredential_templatesIdRouteImport } from './routes/issuer.microcredential_templates.$id'
import { Route as IssuerIssueBulkRouteImport } from './routes/issuer.issue.bulk'
import { Route as EarnerCredentialsIdRouteImport } from './routes/earner.credentials.$id'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuersIndexRoute = IssuersIndexRouteImport.update({
  id: '/issuers/',
  path: '/issuers/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerIndexRoute = IssuerIndexRouteImport.update({
  id: '/issuer/',
  path: '/issuer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerIndexRoute = EarnerIndexRouteImport.update({
  id: '/earner/',
  path: '/earner/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTokenRoute = ProfileTokenRouteImport.update({
  id: '/profile/$token',
  path: '/profile/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuersIdRoute = IssuersIdRouteImport.update({
  id: '/issuers/$id',
  path: '/issuers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerStaffRoute = IssuerStaffRouteImport.update({
  id: '/issuer/staff',
  path: '/issuer/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerRevocationsRoute = IssuerRevocationsRouteImport.update({
  id: '/issuer/revocations',
  path: '/issuer/revocations',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerRequestsRoute = IssuerRequestsRouteImport.update({
  id: '/issuer/requests',
  path: '/issuer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerProfileRoute = IssuerProfileRouteImport.update({
  id: '/issuer/profile',
  path: '/issuer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerEbsiRoute = IssuerEbsiRouteImport.update({
  id: '/issuer/ebsi',
  path: '/issuer/ebsi',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerEarnersRoute = IssuerEarnersRouteImport.update({
  id: '/issuer/earners',
  path: '/issuer/earners',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerCredentialsRoute = IssuerCredentialsRouteImport.update({
  id: '/issuer/credentials',
  path: '/issuer/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerSettingsRoute = EarnerSettingsRouteImport.update({
  id: '/earner/settings',
  path: '/earner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerProfileRoute = EarnerProfileRouteImport.update({
  id: '/earner/profile',
  path: '/earner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerNotificationsRoute = EarnerNotificationsRouteImport.update({
  id: '/earner/notifications',
  path: '/earner/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerApplyRoute = EarnerApplyRouteImport.update({
  id: '/earner/apply',
  path: '/earner/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerApplicationsRoute = EarnerApplicationsRouteImport.update({
  id: '/earner/applications',
  path: '/earner/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerMicrocredential_templatesIndexRoute =
  IssuerMicrocredential_templatesIndexRouteImport.update({
    id: '/issuer/microcredential_templates/',
    path: '/issuer/microcredential_templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuerIssueIndexRoute = IssuerIssueIndexRouteImport.update({
  id: '/issuer/issue/',
  path: '/issuer/issue/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerCredentialsIndexRoute = EarnerCredentialsIndexRouteImport.update({
  id: '/earner/credentials/',
  path: '/earner/credentials/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerMicrocredential_templatesNewRoute =
  IssuerMicrocredential_templatesNewRouteImport.update({
    id: '/issuer/microcredential_templates/new',
    path: '/issuer/microcredential_templates/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuerMicrocredential_templatesIdRoute =
  IssuerMicrocredential_templatesIdRouteImport.update({
    id: '/issuer/microcredential_templates/$id',
    path: '/issuer/microcredential_templates/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const IssuerIssueBulkRoute = IssuerIssueBulkRouteImport.update({
  id: '/issuer/issue/bulk',
  path: '/issuer/issue/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnerCredentialsIdRoute = EarnerCredentialsIdRouteImport.update({
  id: '/earner/credentials/$id',
  path: '/earner/credentials/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/earner/applications': typeof EarnerApplicationsRoute
  '/earner/apply': typeof EarnerApplyRoute
  '/earner/notifications': typeof EarnerNotificationsRoute
  '/earner/profile': typeof EarnerProfileRoute
  '/earner/settings': typeof EarnerSettingsRoute
  '/issuer/credentials': typeof IssuerCredentialsRoute
  '/issuer/earners': typeof IssuerEarnersRoute
  '/issuer/ebsi': typeof IssuerEbsiRoute
  '/issuer/profile': typeof IssuerProfileRoute
  '/issuer/requests': typeof IssuerRequestsRoute
  '/issuer/revocations': typeof IssuerRevocationsRoute
  '/issuer/staff': typeof IssuerStaffRoute
  '/issuers/$id': typeof IssuersIdRoute
  '/profile/$token': typeof ProfileTokenRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/earner/': typeof EarnerIndexRoute
  '/issuer/': typeof IssuerIndexRoute
  '/issuers/': typeof IssuersIndexRoute
  '/earner/credentials/$id': typeof EarnerCredentialsIdRoute
  '/issuer/issue/bulk': typeof IssuerIssueBulkRoute
  '/issuer/microcredential_templates/$id': typeof IssuerMicrocredential_templatesIdRoute
  '/issuer/microcredential_templates/new': typeof IssuerMicrocredential_templatesNewRoute
  '/earner/credentials/': typeof EarnerCredentialsIndexRoute
  '/issuer/issue/': typeof IssuerIssueIndexRoute
  '/issuer/microcredential_templates/': typeof IssuerMicrocredential_templatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/earner/applications': typeof EarnerApplicationsRoute
  '/earner/apply': typeof EarnerApplyRoute
  '/earner/notifications': typeof EarnerNotificationsRoute
  '/earner/profile': typeof EarnerProfileRoute
  '/earner/settings': typeof EarnerSettingsRoute
  '/issuer/credentials': typeof IssuerCredentialsRoute
  '/issuer/earners': typeof IssuerEarnersRoute
  '/issuer/ebsi': typeof IssuerEbsiRoute
  '/issuer/profile': typeof IssuerProfileRoute
  '/issuer/requests': typeof IssuerRequestsRoute
  '/issuer/revocations': typeof IssuerRevocationsRoute
  '/issuer/staff': typeof IssuerStaffRoute
  '/issuers/$id': typeof IssuersIdRoute
  '/profile/$token': typeof ProfileTokenRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin': typeof AdminIndexRoute
  '/earner': typeof EarnerIndexRoute
  '/issuer': typeof IssuerIndexRoute
  '/issuers': typeof IssuersIndexRoute
  '/earner/credentials/$id': typeof EarnerCredentialsIdRoute
  '/issuer/issue/bulk': typeof IssuerIssueBulkRoute
  '/issuer/microcredential_templates/$id': typeof IssuerMicrocredential_templatesIdRoute
  '/issuer/microcredential_templates/new': typeof IssuerMicrocredential_templatesNewRoute
  '/earner/credentials': typeof EarnerCredentialsIndexRoute
  '/issuer/issue': typeof IssuerIssueIndexRoute
  '/issuer/microcredential_templates': typeof IssuerMicrocredential_templatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/earner/applications': typeof EarnerApplicationsRoute
  '/earner/apply': typeof EarnerApplyRoute
  '/earner/notifications': typeof EarnerNotificationsRoute
  '/earner/profile': typeof EarnerProfileRoute
  '/earner/settings': typeof EarnerSettingsRoute
  '/issuer/credentials': typeof IssuerCredentialsRoute
  '/issuer/earners': typeof IssuerEarnersRoute
  '/issuer/ebsi': typeof IssuerEbsiRoute
  '/issuer/profile': typeof IssuerProfileRoute
  '/issuer/requests': typeof IssuerRequestsRoute
  '/issuer/revocations': typeof IssuerRevocationsRoute
  '/issuer/staff': typeof IssuerStaffRoute
  '/issuers/$id': typeof IssuersIdRoute
  '/profile/$token': typeof ProfileTokenRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/earner/': typeof EarnerIndexRoute
  '/issuer/': typeof IssuerIndexRoute
  '/issuers/': typeof IssuersIndexRoute
  '/earner/credentials/$id': typeof EarnerCredentialsIdRoute
  '/issuer/issue/bulk': typeof IssuerIssueBulkRoute
  '/issuer/microcredential_templates/$id': typeof IssuerMicrocredential_templatesIdRoute
  '/issuer/microcredential_templates/new': typeof IssuerMicrocredential_templatesNewRoute
  '/earner/credentials/': typeof EarnerCredentialsIndexRoute
  '/issuer/issue/': typeof IssuerIssueIndexRoute
  '/issuer/microcredential_templates/': typeof IssuerMicrocredential_templatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/registrations'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/earner/applications'
    | '/earner/apply'
    | '/earner/notifications'
    | '/earner/profile'
    | '/earner/settings'
    | '/issuer/credentials'
    | '/issuer/earners'
    | '/issuer/ebsi'
    | '/issuer/profile'
    | '/issuer/requests'
    | '/issuer/revocations'
    | '/issuer/staff'
    | '/issuers/$id'
    | '/profile/$token'
    | '/verify/$id'
    | '/admin/'
    | '/earner/'
    | '/issuer/'
    | '/issuers/'
    | '/earner/credentials/$id'
    | '/issuer/issue/bulk'
    | '/issuer/microcredential_templates/$id'
    | '/issuer/microcredential_templates/new'
    | '/earner/credentials/'
    | '/issuer/issue/'
    | '/issuer/microcredential_templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/registrations'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/earner/applications'
    | '/earner/apply'
    | '/earner/notifications'
    | '/earner/profile'
    | '/earner/settings'
    | '/issuer/credentials'
    | '/issuer/earners'
    | '/issuer/ebsi'
    | '/issuer/profile'
    | '/issuer/requests'
    | '/issuer/revocations'
    | '/issuer/staff'
    | '/issuers/$id'
    | '/profile/$token'
    | '/verify/$id'
    | '/admin'
    | '/earner'
    | '/issuer'
    | '/issuers'
    | '/earner/credentials/$id'
    | '/issuer/issue/bulk'
    | '/issuer/microcredential_templates/$id'
    | '/issuer/microcredential_templates/new'
    | '/earner/credentials'
    | '/issuer/issue'
    | '/issuer/microcredential_templates'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/set-password'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/registrations'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/users'
    | '/earner/applications'
    | '/earner/apply'
    | '/earner/notifications'
    | '/earner/profile'
    | '/earner/settings'
    | '/issuer/credentials'
    | '/issuer/earners'
    | '/issuer/ebsi'
    | '/issuer/profile'
    | '/issuer/requests'
    | '/issuer/revocations'
    | '/issuer/staff'
    | '/issuers/$id'
    | '/profile/$token'
    | '/verify/$id'
    | '/admin/'
    | '/earner/'
    | '/issuer/'
    | '/issuers/'
    | '/earner/credentials/$id'
    | '/issuer/issue/bulk'
    | '/issuer/microcredential_templates/$id'
    | '/issuer/microcredential_templates/new'
    | '/earner/credentials/'
    | '/issuer/issue/'
    | '/issuer/microcredential_templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EarnerApplicationsRoute: typeof EarnerApplicationsRoute
  EarnerApplyRoute: typeof EarnerApplyRoute
  EarnerNotificationsRoute: typeof EarnerNotificationsRoute
  EarnerProfileRoute: typeof EarnerProfileRoute
  EarnerSettingsRoute: typeof EarnerSettingsRoute
  IssuerCredentialsRoute: typeof IssuerCredentialsRoute
  IssuerEarnersRoute: typeof IssuerEarnersRoute
  IssuerEbsiRoute: typeof IssuerEbsiRoute
  IssuerProfileRoute: typeof IssuerProfileRoute
  IssuerRequestsRoute: typeof IssuerRequestsRoute
  IssuerRevocationsRoute: typeof IssuerRevocationsRoute
  IssuerStaffRoute: typeof IssuerStaffRoute
  IssuersIdRoute: typeof IssuersIdRoute
  ProfileTokenRoute: typeof ProfileTokenRoute
  VerifyIdRoute: typeof VerifyIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EarnerIndexRoute: typeof EarnerIndexRoute
  IssuerIndexRoute: typeof IssuerIndexRoute
  IssuersIndexRoute: typeof IssuersIndexRoute
  EarnerCredentialsIdRoute: typeof EarnerCredentialsIdRoute
  IssuerIssueBulkRoute: typeof IssuerIssueBulkRoute
  IssuerMicrocredential_templatesIdRoute: typeof IssuerMicrocredential_templatesIdRoute
  IssuerMicrocredential_templatesNewRoute: typeof IssuerMicrocredential_templatesNewRoute
  EarnerCredentialsIndexRoute: typeof EarnerCredentialsIndexRoute
  IssuerIssueIndexRoute: typeof IssuerIssueIndexRoute
  IssuerMicrocredential_templatesIndexRoute: typeof IssuerMicrocredential_templatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuers/': {
      id: '/issuers/'
      path: '/issuers'
      fullPath: '/issuers/'
      preLoaderRoute: typeof IssuersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/': {
      id: '/issuer/'
      path: '/issuer'
      fullPath: '/issuer/'
      preLoaderRoute: typeof IssuerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/': {
      id: '/earner/'
      path: '/earner'
      fullPath: '/earner/'
      preLoaderRoute: typeof EarnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$token': {
      id: '/profile/$token'
      path: '/profile/$token'
      fullPath: '/profile/$token'
      preLoaderRoute: typeof ProfileTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuers/$id': {
      id: '/issuers/$id'
      path: '/issuers/$id'
      fullPath: '/issuers/$id'
      preLoaderRoute: typeof IssuersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/staff': {
      id: '/issuer/staff'
      path: '/issuer/staff'
      fullPath: '/issuer/staff'
      preLoaderRoute: typeof IssuerStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/revocations': {
      id: '/issuer/revocations'
      path: '/issuer/revocations'
      fullPath: '/issuer/revocations'
      preLoaderRoute: typeof IssuerRevocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/requests': {
      id: '/issuer/requests'
      path: '/issuer/requests'
      fullPath: '/issuer/requests'
      preLoaderRoute: typeof IssuerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/profile': {
      id: '/issuer/profile'
      path: '/issuer/profile'
      fullPath: '/issuer/profile'
      preLoaderRoute: typeof IssuerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/ebsi': {
      id: '/issuer/ebsi'
      path: '/issuer/ebsi'
      fullPath: '/issuer/ebsi'
      preLoaderRoute: typeof IssuerEbsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/earners': {
      id: '/issuer/earners'
      path: '/issuer/earners'
      fullPath: '/issuer/earners'
      preLoaderRoute: typeof IssuerEarnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/credentials': {
      id: '/issuer/credentials'
      path: '/issuer/credentials'
      fullPath: '/issuer/credentials'
      preLoaderRoute: typeof IssuerCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/settings': {
      id: '/earner/settings'
      path: '/earner/settings'
      fullPath: '/earner/settings'
      preLoaderRoute: typeof EarnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/profile': {
      id: '/earner/profile'
      path: '/earner/profile'
      fullPath: '/earner/profile'
      preLoaderRoute: typeof EarnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/notifications': {
      id: '/earner/notifications'
      path: '/earner/notifications'
      fullPath: '/earner/notifications'
      preLoaderRoute: typeof EarnerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/apply': {
      id: '/earner/apply'
      path: '/earner/apply'
      fullPath: '/earner/apply'
      preLoaderRoute: typeof EarnerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/applications': {
      id: '/earner/applications'
      path: '/earner/applications'
      fullPath: '/earner/applications'
      preLoaderRoute: typeof EarnerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/microcredential_templates/': {
      id: '/issuer/microcredential_templates/'
      path: '/issuer/microcredential_templates'
      fullPath: '/issuer/microcredential_templates/'
      preLoaderRoute: typeof IssuerMicrocredential_templatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/issue/': {
      id: '/issuer/issue/'
      path: '/issuer/issue'
      fullPath: '/issuer/issue/'
      preLoaderRoute: typeof IssuerIssueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/credentials/': {
      id: '/earner/credentials/'
      path: '/earner/credentials'
      fullPath: '/earner/credentials/'
      preLoaderRoute: typeof EarnerCredentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/microcredential_templates/new': {
      id: '/issuer/microcredential_templates/new'
      path: '/issuer/microcredential_templates/new'
      fullPath: '/issuer/microcredential_templates/new'
      preLoaderRoute: typeof IssuerMicrocredential_templatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/microcredential_templates/$id': {
      id: '/issuer/microcredential_templates/$id'
      path: '/issuer/microcredential_templates/$id'
      fullPath: '/issuer/microcredential_templates/$id'
      preLoaderRoute: typeof IssuerMicrocredential_templatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer/issue/bulk': {
      id: '/issuer/issue/bulk'
      path: '/issuer/issue/bulk'
      fullPath: '/issuer/issue/bulk'
      preLoaderRoute: typeof IssuerIssueBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earner/credentials/$id': {
      id: '/earner/credentials/$id'
      path: '/earner/credentials/$id'
      fullPath: '/earner/credentials/$id'
      preLoaderRoute: typeof EarnerCredentialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  EarnerApplicationsRoute: EarnerApplicationsRoute,
  EarnerApplyRoute: EarnerApplyRoute,
  EarnerNotificationsRoute: EarnerNotificationsRoute,
  EarnerProfileRoute: EarnerProfileRoute,
  EarnerSettingsRoute: EarnerSettingsRoute,
  IssuerCredentialsRoute: IssuerCredentialsRoute,
  IssuerEarnersRoute: IssuerEarnersRoute,
  IssuerEbsiRoute: IssuerEbsiRoute,
  IssuerProfileRoute: IssuerProfileRoute,
  IssuerRequestsRoute: IssuerRequestsRoute,
  IssuerRevocationsRoute: IssuerRevocationsRoute,
  IssuerStaffRoute: IssuerStaffRoute,
  IssuersIdRoute: IssuersIdRoute,
  ProfileTokenRoute: ProfileTokenRoute,
  VerifyIdRoute: VerifyIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EarnerIndexRoute: EarnerIndexRoute,
  IssuerIndexRoute: IssuerIndexRoute,
  IssuersIndexRoute: IssuersIndexRoute,
  EarnerCredentialsIdRoute: EarnerCredentialsIdRoute,
  IssuerIssueBulkRoute: IssuerIssueBulkRoute,
  IssuerMicrocredential_templatesIdRoute:
    IssuerMicrocredential_templatesIdRoute,
  IssuerMicrocredential_templatesNewRoute:
    IssuerMicrocredential_templatesNewRoute,
  EarnerCredentialsIndexRoute: EarnerCredentialsIndexRoute,
  IssuerIssueIndexRoute: IssuerIssueIndexRoute,
  IssuerMicrocredential_templatesIndexRoute:
    IssuerMicrocredential_templatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
